[package]
name = "file_organizer_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
simple_logger = "5.0.0"
file_organizer_core = { path = "../core" }