[package]
name = "file_organizer_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
log = "0.4"
glob = "0.3"
walkdir = "2.5"
crc = "3.2"